[default]
SECRET_KEY = 'YOUR_SECRET_KEY'
SLACK_WEBHOOK_URL='YOUR_SLACK_WEBHOOK_URL'

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///ip.db'

[production]
SQLALCHEMY_DATABASE_URI = 'YOUR_DATABASE_URI'