[default]
DEBUG = false
EXTENSIONS = [
    "verify_ip.ext.db:init_app",
    "verify_ip.ext.migrate:init_app",
    "verify_ip.ext.routes:init_app"
]

[development]
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = false

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
